/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi.penampil.gambar.gui;

import java.awt.CardLayout;

/**
 *
 * @author Mujahid
 */
public class AplikasiPenampilGambar extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPenampilGambar
     */
    public AplikasiPenampilGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        btmotherboard = new javax.swing.JButton();
        btcpu = new javax.swing.JButton();
        btvga = new javax.swing.JButton();
        btram = new javax.swing.JButton();
        btkeluar = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btmotherboard.setText("Motherboard");
        btmotherboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmotherboardActionPerformed(evt);
            }
        });
        buttonPanel.add(btmotherboard);

        btcpu.setText("CPU");
        btcpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcpuActionPerformed(evt);
            }
        });
        buttonPanel.add(btcpu);

        btvga.setText("VGA");
        btvga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvgaActionPerformed(evt);
            }
        });
        buttonPanel.add(btvga);

        btram.setText("RAM");
        btram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btramActionPerformed(evt);
            }
        });
        buttonPanel.add(btram);

        btkeluar.setText("Keluar");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });
        buttonPanel.add(btkeluar);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmad\\OneDrive\\Pictures\\1.jpg")); // NOI18N
        imagePanel.add(jLabel1, "0");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmad\\OneDrive\\Pictures\\cpu.jpg")); // NOI18N
        imagePanel.add(jLabel2, "1");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmad\\OneDrive\\Pictures\\2.jpg")); // NOI18N
        imagePanel.add(jLabel3, "2");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmad\\OneDrive\\Pictures\\ram.jpg")); // NOI18N
        imagePanel.add(jLabel4, "3");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmotherboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmotherboardActionPerformed
        CardLayout c1 = (CardLayout) (imagePanel.getLayout());
        c1.show(imagePanel,"0");
    }//GEN-LAST:event_btmotherboardActionPerformed

    private void btcpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcpuActionPerformed
       CardLayout c1 = (CardLayout) (imagePanel.getLayout());
        c1.show(imagePanel,"1");
    }//GEN-LAST:event_btcpuActionPerformed

    private void btvgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvgaActionPerformed
        CardLayout c1 = (CardLayout) (imagePanel.getLayout());
        c1.show(imagePanel,"2");
    }//GEN-LAST:event_btvgaActionPerformed

    private void btramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btramActionPerformed
        CardLayout c1 = (CardLayout) (imagePanel.getLayout());
        c1.show(imagePanel,"3");
    }//GEN-LAST:event_btramActionPerformed

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenampilGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcpu;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton btmotherboard;
    private javax.swing.JButton btram;
    private javax.swing.JButton btvga;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
